// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

package taskmanager_sdk

import (
	"bytes"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"math"
	mrand "math/rand"
	"net/http"
	"net/url"
	"runtime"
	"os"
	"strconv"
	"strings"
	"time"
)

// LogLevel represents the SDK logging verbosity.
type LogLevel int

const (
	LogOff   LogLevel = 0
	LogError LogLevel = 1
	LogWarn  LogLevel = 2
	LogInfo  LogLevel = 3
	LogDebug LogLevel = 4
)

func parseLogLevel(s string) LogLevel {
	switch strings.ToLower(s) {
	case "debug":
		return LogDebug
	case "info":
		return LogInfo
	case "warn":
		return LogWarn
	case "error":
		return LogError
	case "off":
		return LogOff
	default:
		return LogWarn
	}
}

// RequestOptions provides per-request overrides for headers and timeout.
type RequestOptions struct {
	// Headers to merge with the request. Nil-valued entries are ignored.
	Headers map[string]string
	// Timeout overrides the client-level timeout when non-zero.
	Timeout time.Duration
}

type Client struct {
	BaseURL    string
	APIKey     string
	Headers    map[string]*string
	HTTPClient *http.Client
	MaxRetries int
	Timeout    time.Duration
	LogLevel   LogLevel
	Logger     *log.Logger
}

// mergeHeaders merges multiple header sources. Later sources override earlier ones
// using case-insensitive matching. A nil value removes the header.
func mergeHeaders(base http.Header, overrides ...map[string]*string) http.Header {
	merged := base.Clone()
	for _, src := range overrides {
		if src == nil {
			continue
		}
		for key, value := range src {
			canonical := http.CanonicalHeaderKey(key)
			if value == nil {
				merged.Del(canonical)
			} else {
				merged.Set(canonical, *value)
			}
		}
	}
	return merged
}

var retryableStatusCodes = map[int]bool{
	408: true,
	409: true,
	429: true,
}

func isRetryableStatus(code int) bool {
	return code >= 500 || retryableStatusCodes[code]
}

func retryDelay(attempt int) time.Duration {
	baseMs := 500.0 * math.Pow(2, float64(attempt))
	jitterMs := mrand.Float64() * baseMs * 0.25
	return time.Duration(baseMs+jitterMs) * time.Millisecond
}

func parseRetryAfter(headerValue string) (time.Duration, bool) {
	if headerValue == "" {
		return 0, false
	}
	if seconds, err := strconv.Atoi(headerValue); err == nil {
		d := time.Duration(seconds) * time.Second
		if d < 0 {
			d = 0
		}
		if d > 60*time.Second {
			d = 60 * time.Second
		}
		return d, true
	}
	if t, err := time.Parse(time.RFC1123, headerValue); err == nil {
		d := time.Until(t)
		if d < 0 {
			d = 0
		}
		if d > 60*time.Second {
			d = 60 * time.Second
		}
		return d, true
	}
	return 0, false
}

// ClientOption is a functional option for configuring the Client.
type ClientOption func(*Client)

// WithHTTPClient sets a custom *http.Client for the SDK client.
func WithHTTPClient(hc *http.Client) ClientOption {
	return func(c *Client) {
		c.HTTPClient = hc
	}
}

func NewClient(baseURL string, apiKey string, opts ...ClientOption) *Client {
	if baseURL == "" {
		if envURL := os.Getenv("VERS_BASE_URL"); envURL != "" {
			baseURL = envURL
		}
	}
	if apiKey == "" {
		if envKey := os.Getenv("VERS_API_KEY"); envKey != "" {
			apiKey = envKey
		}
	}
	envLogLevel := parseLogLevel(os.Getenv("VERS_LOG"))
	c := &Client{
		BaseURL:    baseURL,
		APIKey:     apiKey,
		Headers:    nil,
		HTTPClient: &http.Client{},
		MaxRetries: 2,
		Timeout:    30 * time.Second,
		LogLevel:   envLogLevel,
		Logger:     log.New(os.Stderr, "[vers_sdk] ", log.LstdFlags),
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *Client) logf(level LogLevel, format string, args ...interface{}) {
	if c.LogLevel >= level && c.Logger != nil {
		c.Logger.Printf(format, args...)
	}
}

func isMutatingMethod(method string) bool {
	switch strings.ToUpper(method) {
	case "POST", "PUT", "PATCH", "DELETE":
		return true
	}
	return false
}

func generateIdempotencyKey() string {
	b := make([]byte, 16)
	_, _ = rand.Read(b)
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

func (c *Client) doRequest(method, path string, body interface{}, opts ...*RequestOptions) (*http.Response, error) {
	var opt *RequestOptions
	for _, o := range opts {
		if o != nil {
			opt = o
			break
		}
	}
	c.logf(LogDebug, "request: %s %s", method, path)
	idempotencyKey := ""
	if isMutatingMethod(method) {
		idempotencyKey = generateIdempotencyKey()
	}
	var lastErr error
	retryAfterUsed := false
	for attempt := 0; attempt <= c.MaxRetries; attempt++ {
		if attempt > 0 && !retryAfterUsed {
			c.logf(LogInfo, "retry attempt %d/%d for %s %s", attempt, c.MaxRetries, method, path)
			time.Sleep(retryDelay(attempt - 1))
		}
		retryAfterUsed = false

		var reqBody io.Reader
		if body != nil {
			jsonBody, err := json.Marshal(body)
			if err != nil {
				return nil, fmt.Errorf("marshal body: %w", err)
			}
			reqBody = bytes.NewBuffer(jsonBody)
		}
		req, err := http.NewRequest(method, c.BaseURL+path, reqBody)
		if err != nil {
			return nil, fmt.Errorf("create request: %w", err)
		}
		defaultHeaders := make(http.Header)
		defaultHeaders.Set("Content-Type", "application/json")
		defaultHeaders.Set("User-Agent", fmt.Sprintf("taskmanager-sdk/0.2.0 go/%s %s/%s", runtime.Version(), runtime.GOOS, runtime.GOARCH))
		if c.APIKey != "" {
			defaultHeaders.Set("Authorization", "Bearer "+c.APIKey)
		}
		if idempotencyKey != "" {
			defaultHeaders.Set("X-Idempotency-Key", idempotencyKey)
		}
		req.Header = mergeHeaders(defaultHeaders, c.Headers)
		// Apply per-request header overrides
		if opt != nil {
			for k, v := range opt.Headers {
				req.Header.Set(k, v)
			}
		}

		effectiveTimeout := c.Timeout
		if opt != nil && opt.Timeout > 0 {
			effectiveTimeout = opt.Timeout
		}
		client := c.HTTPClient
		if client.Timeout == 0 && effectiveTimeout > 0 {
			client = &http.Client{Timeout: effectiveTimeout}
		}
		resp, err := client.Do(req)
		if err != nil {
			c.logf(LogError, "connection error: %s %s - %v", method, path, err)
			lastErr = &ConnectionError{Message: err.Error(), Cause: err}
			if attempt == c.MaxRetries {
				return nil, lastErr
			}
			continue
		}
		c.logf(LogDebug, "response: %d for %s %s", resp.StatusCode, method, path)
		if isRetryableStatus(resp.StatusCode) && attempt < c.MaxRetries {
			if d, ok := parseRetryAfter(resp.Header.Get("Retry-After")); ok {
				retryAfterUsed = true
				c.logf(LogInfo, "retry attempt %d/%d for %s %s (retry-after: %v)", attempt+1, c.MaxRetries, method, path, d)
				time.Sleep(d)
			}
			resp.Body.Close()
			lastErr = fmt.Errorf("HTTP %d", resp.StatusCode)
			continue
		}
		if resp.StatusCode < 200 || resp.StatusCode >= 300 {
			defer resp.Body.Close()
			bodyBytes, _ := io.ReadAll(resp.Body)
			return nil, NewAPIError(resp.StatusCode, resp.Header, string(bodyBytes))
		}
		return resp, nil
	}
	return nil, lastErr
}

// ListTasks - List all tasks
func (c *Client) ListTasks(params *ListTasksParams, opts ...*RequestOptions) (*TaskListResponse, error) {
	reqPath := "/api/tasks"
	qp := url.Values{}
	if params != nil {
		if params.Status != nil {
			qp.Set("status", fmt.Sprintf("%v", *params.Status))
		}
		if params.Limit != nil {
			qp.Set("limit", fmt.Sprintf("%v", *params.Limit))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty TaskListResponse
		return &empty, nil
	}
	var result TaskListResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// CreateTask - Create a new task
func (c *Client) CreateTask(body interface{}, opts ...*RequestOptions) (*Task, error) {
	reqPath := "/api/tasks"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty Task
		return &empty, nil
	}
	var result Task
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// GetTask - Get a task by ID
func (c *Client) GetTask(task_id string, opts ...*RequestOptions) (*Task, error) {
	reqPath := fmt.Sprintf("/api/tasks/%s", task_id)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty Task
		return &empty, nil
	}
	var result Task
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// DeleteTask - Delete a task
func (c *Client) DeleteTask(task_id string, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/tasks/%s", task_id)
	resp, err := c.doRequest("DELETE", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// UpdateTask - Update a task
func (c *Client) UpdateTask(task_id string, body interface{}, opts ...*RequestOptions) (*Task, error) {
	reqPath := fmt.Sprintf("/api/tasks/%s", task_id)
	resp, err := c.doRequest("PATCH", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty Task
		return &empty, nil
	}
	var result Task
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// CompleteTask - Mark a task as done
func (c *Client) CompleteTask(task_id string, body interface{}, opts ...*RequestOptions) (*Task, error) {
	reqPath := fmt.Sprintf("/api/tasks/%s/complete", task_id)
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty Task
		return &empty, nil
	}
	var result Task
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

