// Generated by Sterling SDK Generator — test suite
// Task Manager API v0.2.0

package taskmanager_sdk

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// captured holds details about the last request received by the test server.
type captured struct {
	Method string
	Path   string
	Body   string
}

func setupTestServer(t *testing.T) (*httptest.Server, *captured) {
	t.Helper()
	cap := &captured{}
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		cap.Method = r.Method
		cap.Path = r.URL.RequestURI()
		if r.Body != nil {
			bodyBytes, _ := io.ReadAll(r.Body)
			cap.Body = string(bodyBytes)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	}))
	return ts, cap
}

func setupErrorServer(t *testing.T, statusCode int) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(statusCode)
		_ = json.NewEncoder(w).Encode(map[string]string{"message": "error"})
	}))
}

func TestListTasks_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListTasks(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestCreateTask_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.CreateTask(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestGetTask_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.GetTask("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeleteTask_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeleteTask("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "DELETE" {
		t.Errorf("method: got %s, want DELETE", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestUpdateTask_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.UpdateTask("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PATCH" {
		t.Errorf("method: got %s, want PATCH", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestCompleteTask_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.CompleteTask("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestErrorHandling_400(t *testing.T) {
	ts := setupErrorServer(t, 400)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListTasks(nil)
	if err == nil {
		t.Fatal("expected error on 400")
	}
	var apiErr *APIError
	if ok := isAPIError(err, &apiErr); !ok {
		t.Fatalf("expected APIError, got %T", err)
	}
	if apiErr.Status != 400 {
		t.Errorf("status: got %d, want 400", apiErr.Status)
	}
}

func TestErrorHandling_404(t *testing.T) {
	ts := setupErrorServer(t, 404)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListTasks(nil)
	if err == nil {
		t.Fatal("expected error on 404")
	}
}

func TestErrorHandling_500(t *testing.T) {
	ts := setupErrorServer(t, 500)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListTasks(nil)
	if err == nil {
		t.Fatal("expected error on 500")
	}
}

// isAPIError checks whether err is *APIError (via errors.As equivalent).
func isAPIError(err error, target **APIError) bool {
	if e, ok := err.(*APIError); ok {
		*target = e
		return true
	}
	return false
}
