// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

package taskmanager_sdk

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// SDKError is the base error type for the SDK.
type SDKError struct {
	Message string
}

func (e *SDKError) Error() string {
	return e.Message
}

// APIError represents an error response from the API.
type APIError struct {
	Status  int
	Headers http.Header
	Body    string
	Kind    APIErrorKind
}

// APIErrorKind categorizes API errors by status code.
type APIErrorKind int

const (
	APIErrorKindOther APIErrorKind = iota
	APIErrorKindBadRequest
	APIErrorKindAuthentication
	APIErrorKindPermissionDenied
	APIErrorKindNotFound
	APIErrorKindConflict
	APIErrorKindUnprocessableEntity
	APIErrorKindRateLimit
	APIErrorKindInternalServer
)

func (e *APIError) Error() string {
	return fmt.Sprintf("%d %s", e.Status, e.Body)
}

// ErrorMessage extracts the human-readable error message from the response.
// If the body is JSON with an "error" or "message" field, returns that.
// Otherwise returns the raw body text.
func (e *APIError) ErrorMessage() string {
	var m map[string]interface{}
	if err := json.Unmarshal([]byte(e.Body), &m); err == nil {
		if msg, ok := m["error"].(string); ok {
			return msg
		}
		if msg, ok := m["message"].(string); ok {
			return msg
		}
	}
	return e.Body
}

// NewAPIError creates an APIError from an HTTP response status, headers, and body.
func NewAPIError(status int, headers http.Header, body string) *APIError {
	var kind APIErrorKind
	switch status {
	case 400:
		kind = APIErrorKindBadRequest
	case 401:
		kind = APIErrorKindAuthentication
	case 403:
		kind = APIErrorKindPermissionDenied
	case 404:
		kind = APIErrorKindNotFound
	case 409:
		kind = APIErrorKindConflict
	case 422:
		kind = APIErrorKindUnprocessableEntity
	case 429:
		kind = APIErrorKindRateLimit
	default:
		if status >= 500 {
			kind = APIErrorKindInternalServer
		} else {
			kind = APIErrorKindOther
		}
	}
	return &APIError{Status: status, Headers: headers, Body: body, Kind: kind}
}

// IsBadRequest returns true if this is a 400 error.
func (e *APIError) IsBadRequest() bool { return e.Kind == APIErrorKindBadRequest }

// IsAuthentication returns true if this is a 401 error.
func (e *APIError) IsAuthentication() bool { return e.Kind == APIErrorKindAuthentication }

// IsPermissionDenied returns true if this is a 403 error.
func (e *APIError) IsPermissionDenied() bool { return e.Kind == APIErrorKindPermissionDenied }

// IsNotFound returns true if this is a 404 error.
func (e *APIError) IsNotFound() bool { return e.Kind == APIErrorKindNotFound }

// IsConflict returns true if this is a 409 error.
func (e *APIError) IsConflict() bool { return e.Kind == APIErrorKindConflict }

// IsUnprocessableEntity returns true if this is a 422 error.
func (e *APIError) IsUnprocessableEntity() bool { return e.Kind == APIErrorKindUnprocessableEntity }

// IsRateLimit returns true if this is a 429 error.
func (e *APIError) IsRateLimit() bool { return e.Kind == APIErrorKindRateLimit }

// IsInternalServer returns true if this is a 5xx error.
func (e *APIError) IsInternalServer() bool { return e.Kind == APIErrorKindInternalServer }

// ConnectionError represents a failure to connect to the API.
type ConnectionError struct {
	Message   string
	IsTimeout bool
	Cause     error
}

func (e *ConnectionError) Error() string {
	if e.Cause != nil {
		return fmt.Sprintf("connection error: %s: %v", e.Message, e.Cause)
	}
	return fmt.Sprintf("connection error: %s", e.Message)
}

func (e *ConnectionError) Unwrap() error {
	return e.Cause
}
