// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

package taskmanager_sdk

// 
type Task struct {
	Id string `json:"id"`
	Title string `json:"title"`
	Description string `json:"description,omitempty"`
	Status string `json:"status"`
	Priority int64 `json:"priority"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	DueDate string `json:"due_date,omitempty"`
}

// 
type TaskListResponse struct {
	Tasks []Task `json:"tasks"`
	Total int64 `json:"total"`
}

// 
type ErrorResponse struct {
	// Human-readable error message
	Error string `json:"error"`
	// Always false for errors
	Success bool `json:"success"`
}

// 
type CreateTaskRequest struct {
	// Task title (required)
	Title string `json:"title"`
	// Optional description
	Description string `json:"description,omitempty"`
	// Priority (0 = default)
	Priority int64 `json:"priority,omitempty"`
	DueDate string `json:"due_date,omitempty"`
}

// 
type UpdateTaskRequest struct {
	Title string `json:"title,omitempty"`
	Description string `json:"description,omitempty"`
	Status string `json:"status,omitempty"`
	Priority int64 `json:"priority,omitempty"`
	DueDate string `json:"due_date,omitempty"`
}


// ── Params types for operations with query parameters ───────────────

// ListTasksParams holds optional query parameters.
type ListTasksParams struct {
	Status *string `json:"status,omitempty"`
	Limit *int64 `json:"limit,omitempty"`
}

